### ISSUE TITLE
Example Needed

### ISSUE THREAD

**Issue by Abdullah0991** [NathanAdhitya/express-mongoose-ra-json-server#1]
HI,
Can you provide a real-world example of using this provider?

**Comment by NathanAdhitya** [comment]
Hello. Thank you for the suggestion. I will add an example repo later. Feel free to tag me again after 2 days if I have not gotten it up.

**Comment by Abdullah0991** [comment]
@NathanAdhitya UP!

**Comment by NathanAdhitya** [comment]
Hello. Sorry for the late reply.
Here is the repository. https://github.com/NathanAdhitya/express-mongoose-ra-json-server-demo
Let me know if there are any troubles running it.
