### ISSUE TITLE
How to add logic in the router?

### ISSUE THREAD

**Issue by paulatsydney** [NathanAdhitya/express-mongoose-ra-json-server#2]
Let me use your express-mongoose-ra-json-server-demo as example.

If there is an additional field in User model:
Posts : {type: [Schema.Type.ObjectId]}
When user created a post, we can use mongoose transaction to add objectId of the newly created post into above array of User. 
I believe this is quite common in business requirement.

How to achieve that by using this library?

**Comment by NathanAdhitya** [comment]
Hello, your use case seems to be interesting. Usually, I just query it the other way around to prevent duplicate data.
Index the User in the Post, and if you need to get posts from a user, just query the Post model.

It is implemented as how I said in the demo. Could you elaborate further?
PS You could technically expand the User Resource in the frontend to display such relations with reference fields.

**Comment by paulatsydney** [comment]
Thanks for your quick response.

I agree with your approach to avoid data duplication. Using "Index the User" sounds can fulfill that requirement on frontend - Display posts belong to one user.

While you answers implies that we can't change the logic inside the route. Let me give an example:
In library, there are books:
Book
{name: String, count: Number}
User:
{name: String: books: [String]}
When user borrow one book from library, a book is added to books of User. In the same time, the count of book should reduce 1. We can use Transaction to achieve it in route usually.
Would you please share your thoughts how you can solve it here?

**Comment by NathanAdhitya** [comment]
I'm not sure how I would implement the idea of side effects like so. Nevertheless, your ideas and PRs are welcome to improve this.

But if you're looking for custom routes, you can disable the route provided for certain actions with the option `capabilities` when calling the raExpressMongoose function and supply it with a custom router with the `router` option. That way, you will have full control over the code that executes on that route.

In hindsight, I just noticed that I may have forgotten to export the helper functions that do the id conversions, and some others. Might export those in the next release.

**Comment by NathanAdhitya** [comment]
Hello, the newest build (v0.1.0) exports some of the helper functions. Let me know what you think.

**Comment by paulatsydney** [comment]
Thanks Nathan!! I see you exports few modules in util. I'll try to see how to use it.
