### ISSUE TITLE
TypeError: raExpressMongoose is not a function

### ISSUE THREAD

**Issue by mulder1628** [NathanAdhitya/express-mongoose-ra-json-server#3]
Hi Nathan, 
I am a newbie to this library and react-admin.  Please bear with me if this is blatant config issue on my part.

i "npm add express-mongoose-ra-json-server" on the server side, and created a metadataRoutes.js with the following:

```
import express from 'express'
import raExpressMongoose from "express-mongoose-ra-json-server";
import Metadata from "../models/metadataModel.js";

const router = express.Router()
router.use("/metadata", raExpressMongoose(Metadata));
export default router;
```

and included in the server.js file as follows:

```
import express from 'express'
import metadataRoutes from './routes/metadataRoutes.js'
const app = express()
app.use('/', metadataRoutes)
```

however, when start, i got this error:
router.use("/metadata", raExpressMongoose(Metadata));
                                        ^
TypeError: raExpressMongoose is not a function

I looked thru the index.ts, and didn't see anything jump out as to why this is happening.  Can you help?

Thanks!

**Comment by NathanAdhitya** [comment]
Hello, thank you for the question. You seem new to Github.
Next time, please consider putting your code in code blocks to improve readability :D
\`\`\`ts
your code here
\`\`\`

Anyways, thank you for the report. 

I believe you're trying to use ESM imports within your project. I do know that it works with CommonJS, but I have not fully tested it with ESM. I will try to replicate it on my side and figure out what is wrong. Tag me in two days if no response from me appears.

**Comment by mulder1628** [comment]
Hi Nathan,
Thanks for the prompt reply.  My apology for the legibility issue. 
Let me check with CommonJS as well.  Will ping you in 2 days if no reply. thx again!

**Comment by NathanAdhitya** [comment]
Actually, my mistake. I thought that was regular JS. Turns out you're using TypeScript. If you could post your tsconfig.json, it would help me diagnose easier later.

**Comment by mulder1628** [comment]
My apology, it is regular JS.  I don't have tsconfig.json in my project.

**Comment by NathanAdhitya** [comment]
Oh, ok. Will try and check later. Thank you for the report.

**Comment by NathanAdhitya** [comment]
Hello. I was able to confirm your issue on my side. The latest build (v0.1.0) should now have proper build tools to build for both ESM and CJS. Try updating to the latest version. Let me know if it works for you. If it does, feel free to reply and close the issue.

**Comment by mulder1628** [comment]
Hi Nathan,
The new version works flawlessly.  Thank you so much for the quick fix to address the issue!
You are awesome!
