### ISSUE TITLE
X-Total-Count header is missing in the HTTP Response

### ISSUE THREAD

**Issue by mulder1628** [NathanAdhitya/express-mongoose-ra-json-server#4]
Hi Nathan,

I am using this library on the server side (localhost:5050), with cors() set in the express server.
I run frontend on localhost:18180, calling http://localhost:5050

When I access the api to fetch the mongodb via this library, i got this error on the frontend ra side:

ra client side:
```
    "ra-data-json-server": "^4.3.3",
    "react": "^18.2.0",
    "react-admin": "^4.3.3",
    "react-dom": "^18.2.0",

```

`The X-Total-Count header is missing in the HTTP Response. The jsonServer Data Provider expects responses for lists of resources to contain this header with the total number of results to build the pagination. If you are using CORS, did you declare X-Total-Count in the Access-Control-Expose-Headers header?`

server side:
```
    "express": "^4.17.1",
    "express-mongoose-ra-json-server": "^0.1.0",

```
Wondering if there is a way to tell raExpressMongooseOptions to inject the total in the http response to satisfy this ra requirement?

This is more of a feature ask, but this library would save me lots of rewriting of simple CRUD to make ra happy if it includes this in the header.

Thank you so much in advance!

**Comment by NathanAdhitya** [comment]
Hello, the library does inject X-Total-Count into the header.
It may be something to do with your CORS implementation. Could you provide more details on how you're doing your backend side of the code?

**Comment by mulder1628** [comment]
Hi Nathan,
I added the following, applying cors() to all routes.

cors version:
`    "cors": "^2.8.5",
`
server.js:
```
const corsOptions = {
  exposedHeaders: ['X-Total-Count'],
};

app.use(cors());
app.use(express.json());

```
And I saw this going thru in the response header.
Thanks so much!

**Comment by mulder1628** [comment]
Hi Nathan,
```
const corsOptions = {
  exposedHeaders: ['X-Total-Count'],
};

app.use(cors());
app.use(express.json());

```
Now, I saw this X-Total-Count is coming thru in the response header.  I am closing this issue.
Thanks so much!
