### ISSUE TITLE
Unable to use Mongoose virtual attributes

### ISSUE THREAD

**Issue by GoldwingDesigns** [NathanAdhitya/express-mongoose-ra-json-server#6]
Thanks so much for your resource!

I have tried setting up a Schema to include a "virtual" attribute for 'fullName'.  However once I get the user from the database (i.e. on a React-Admin "Show" Page), the 'fullName' attribute returns undefined.  I have tried endless troubleshooting and don't see any of my code that might be causing this.  Might this be a limitation of the ra-json-server?  

Thanks for the help

```
import mongoose, { Schema } from "mongoose";
import Int32 from "mongoose-int32";

Int32.loadType(mongoose);

const userSchema = new Schema(
  {
    firstName: {
      type: String,
      required: [true, "Please add a first name"],
    },
    lastName: {
      type: String,
      default: "Smith",
      required: [true, "Please add a last name"],
    },
    avatar: {
      data: Buffer,
      contentType: String,
    },
    gender: {
      type: String,
      enum: ["Male", "Female"],
    },
    age: {
      type: Int32,
    },
},
      { timestamps: true }
);
userSchema.set("toObject", { virtuals: true });
userSchema.set("toJSON", { virtuals: true });
userSchema.virtual("fullName").get(function () {
  return this.firstName + " " + this.lastName;
});

export default mongoose.model("User", userSchema);
```

**Comment by NathanAdhitya** [comment]
Hello, there seems to be nothing wrong with your code. 
I must mention that the current method of getting the data from mongoose is to use .lean() in the query for performance reasons, hence the model's virtuals won't run, as documented in the mongoose wiki. https://mongoosejs.com/docs/tutorials/lean.html
https://github.com/NathanAdhitya/express-mongoose-ra-json-server/blob/0d24f5e46f574c3b6ce0f0e61caedbf682732953/src/index.ts#L179-L188

I can see the use case for using virtuals on this library, hence I'm considering either removing the .lean or making it optional. As of now, one way out is to declare your own router, disable the show capability, and add your own show route that does not use .lean.

I'm waiting for more opinions on this subject. Let me know if you have more ideas.

**Comment by GoldwingDesigns** [comment]
Thanks for the quick response.

Now I better understand the issue with lean.  I did notice this plugin which allows virtuals with lean... [https://plugins.mongoosejs.io/plugins/lean-virtuals](https://plugins.mongoosejs.io/plugins/lean-virtuals).  However the plugin requires setting a '{ virtuals: true }' object to .lean() when calling find.

I may eventually try declaring my own router, but for now have just made a simple helper function to get the 'fullName' for me from the first and last name.

**Comment by NathanAdhitya** [comment]
Hello, the library has been updated to have an option for useLean: false. Let me know if it works. I will close the issue if there is no response after 2 days. Thanks for your support!
