### ISSUE TITLE
Filter Operators

### ISSUE THREAD

**Issue by paulr113** [NathanAdhitya/express-mongoose-ra-json-server#7]
Hello,
would it be possible to add support for filter operators?
Currently it is not possible to use MongoDB operators like `$gte` or `$lte`.
There is a section about this in the [react-admin documentation](https://marmelab.com/react-admin/FilteringTutorial.html#filter-operators).

**Comment by NathanAdhitya** [comment]
Hello. I think that is a great idea and it is possible. Although I don't think I currently have the time to do that in the near future. I'll get to it if I do, but for now, your PRs are highly welcome :)

**Comment by paulr113** [comment]
Ok. I will code up a PR 👍

**Comment by paulr113** [comment]
@NathanAdhitya Please take a look at #8

**Comment by NathanAdhitya** [comment]
Associated #8 has been merged. Thank you for your contribution.

**Comment by ixbalazs** [comment]
@NathanAdhitya , can we have a npm update to be able to install the latest version including these operators?
