### ISSUE TITLE
q? string case sensitive

### ISSUE THREAD

**Issue by hzgand** [NathanAdhitya/express-mongoose-ra-json-server#9]
The API query parameter `q` is case sensitive when searching within mongoose fields, when it should not be.

Looking at the demo JSON server, the query string on its API is not case sensitive:

The query with search string "est rerum"
https://jsonplaceholder.typicode.com/posts?q=est%20rerum
returns the following JSON:
```
[
  {
    "userId": 1,
    "id": 2,
    "title": "qui est esse",
    "body": "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla"
  }
]
```

The query with search string "eST reRuM" also located the same entry
https://jsonplaceholder.typicode.com/posts?q=eST%20reRuM
```
[
  {
    "userId": 1,
    "id": 2,
    "title": "qui est esse",
    "body": "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla"
  }
]
```

However, in my usage I have found it to be case sensitive instead, so a query for "eST reRuM" would not find any entries.

This should be fixed or an option added to make text searches case insensitive.

**Comment by NathanAdhitya** [comment]
You have a fair point. I've experienced the same frustration sometimes. Although I'm not sure how it should be implemented correctly. Should it be passed as a configuration option on the client or on the server? As of now, the string is simply escaped and then converted into regex. 🤔

**Comment by NathanAdhitya** [comment]
Added by default in commit f9fe7d37c1f27cd4ccc69db35356a1141875a235.
Use regexFlags parameters to specify your desired regex parameters.
